# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:48
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, default='', max_length=255)),
                ('media', models.ImageField(
                    blank=True, null=True, upload_to='images/')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='children', to='tweets.Tweet')),
                ('user_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, default=django.utils.timezone.now)),
                ('is_reply', models.BooleanField(default=False))
            ],
        ),
    ]
