# Generated by Django 4.2.2 on 2023-06-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
