# Generated by Django 4.2.2 on 2023-07-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profilePic/')),
                ('bgp', models.ImageField(blank=True, null=True, upload_to='bgPic/')),
                ('display_name', models.CharField(blank=True, default='')),
                ('bio', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('birthdate', models.DateField(blank=True, default='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
