# Generated by Django 4.2.4 on 2023-08-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='static/images/default2.webp', upload_to='profilePic/'),
        ),
    ]
