import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Landing from '../components/Landing'
import Layout from '../hocs/Layout'
import { useDispatch, useSelector } from 'react-redux'
import { check_auth_status } from '../actions/auth'
import { useEffect } from 'react'
import Modal from '../components/Modal'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    if (dispatch && dispatch !== null && dispatch !== undefined) {
      dispatch(check_auth_status());//place the load process in this action
      //dispatch(request_refresh()); //this prolly woudnt be done in a real application, this would only be hit on very important pages, li
      //like maybe a checkout page 

    }
  }, [dispatch])

  const isAuthenticated = useSelector(state => state.auth.isAuthenticated)
  const isModal = useSelector(state => state.tweets.isModal)
  if (isAuthenticated === false) {
    return (
      <>
        <Head>
          <title>Bird app</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Landing />
        </main>
      </>
    )
  }


  return (
    <>
      <Head>
        <title>Bird app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen max-w-[1500px] flex mx-auto">

        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}
        <Feed />
        {/* Widgets */}

        {isModal && <Modal />}
      </main>

    </>
  )
}
