import Head from 'next/head'
import React from 'react'
import { Inter } from '@next/font/google'
import Sidebar from '../../components/Sidebar'
import Landing from '../../components/Landing'
import Post from '../../components/Post'
import { useDispatch, useSelector } from 'react-redux'
import { check_auth_status } from '../../actions/auth'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { ArrowLeftIcon } from '@heroicons/react/outline'
import PacmanLoader from "react-spinners/PacmanLoader";
import Reply from '../../components/Reply'
import { get_replies } from '../../actions/tweets'
import RightSidebar from '../../components/RightSidebar'
import Modal from '../../components/Modal'
import { get_user_profile } from '../../actions/profile'
import SearchSlide from '../../components/SearchSlide'
import LowerNav from '../../components/LowerNav'

const inter = Inter({ subsets: ['latin'] })

export default function TweetPage() {
    const router = useRouter();
    const dispatch = useDispatch();
    const isAuthenticated = useSelector(state => state.auth.isAuthenticated)
    const [tweet, setTweet] = useState()
    const mainUsername = useSelector(state => state.auth.user?.username)
    const [tweet_id, setTweet_Id] = useState(null) 
    const [loading, setLoading] = useState(false) //https://www.davidhu.io/react-spinners/
    
    const replies =  useSelector(state => state.tweets.replies)
    const mainProfile = useSelector(state=>state.profile?.mainProfile[0])
    const isModal = useSelector(state => state.tweets.isModal)

    const tweetData = useSelector(state => state.tweets.tweetData)
    
    const [toggleSearchSlide, setToggleSearchSlide] = useState(false)
    
    useEffect( () =>{
        setLoading(true)
        if(router.isReady){
            //setTweet_Id(router.query['id'])
            console.log(router.query['id'])

            async function getTweet(){

                try {
                    console.log(1)
                    const res = await fetch(`${process.env.DJANGO_API_URL}/api/tweets/retrieveTweet/${router.query['id']}`, {
                        method: 'GET'
                    })
                    console.log(router.query['id'])
                    dispatch(get_replies(router.query['id']))
                    const data = await res.json()
                    console.log(data)
                    setTweet(data)
                    setLoading(false)
                    
                    
                } catch (error) {
                    console.log(error)
                }

                
            }
            getTweet();
            
            
        }
    },[router.isReady])
    
    //async function getTweet(){
        //     try {
        //         console.log(id)
        //         const res = await axios.get(`http://localhost:8000/api/tweets/retrieveTweet/${id}`)
        //         console.log(id)
        //         setTweet(res.data)

                
        //     } catch (error) {
        //         // if(error.response)
        //         // {
        //         //     // The request was made and the server responded with a status code
        //         //     // that falls out of the range of 2xx
        //         //     console.log(error.response.data);
        //         //     console.log(error.response.status);
        //         // }
        //         // else{
        //         //     // Something happened in setting up the request that triggered an Error
        //         //     console.log('Error', error.message);
        //         // }
        //         console.log('Error', error.message)
             
        //     }
        //     return console.log(tweet)
    
        // }

        // getTweet();
  
  
  
  
 
  
  useEffect(()=>{
        if(dispatch && dispatch !== null && dispatch !== undefined ){
            dispatch(check_auth_status());//place the load process in this action
            //dispatch(request_refresh()); //this prolly woudnt be done in a real application, this would only be hit on very important pages, li
            //like maybe a checkout page 
            
        }
    },[dispatch])

    useEffect(()=>{
      dispatch(get_user_profile(mainUsername, true))
    },[mainUsername])
   
    
  
  
  if(isAuthenticated === false){
    return (
      <>
        <Head>
        <title>Bird app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Landing/>
        </main>
      </>
    )
  }


  return (
    <>
      <Head>
        <title>{router.query['user']} on Twitter "{tweet?.tweet[0]?.text}"</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen max-w-[1500px] flex mx-auto">

        {/* Sidebar */}
        <Sidebar/>
        <div className="relative flex-grow border-l border-r border-gray-700 max-w-2xl sm:ml-[73px] xl:ml-[370px]">
            <SearchSlide setToggleSearchSlide={setToggleSearchSlide} toggleSearchSlide={toggleSearchSlide}/>
                  

          <div className="flex items-center px-1.5 py-2 border-b border-gray-700 text-[#d9d9d9] font-semibold text-xl gap-x-4 sticky top-0 z-50 bg-black">
            <div
              className="hoverAnimation w-9 h-9 flex items-center justify-center xl:px-0"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="h-5 text-white" />
            </div>
            Tweet
          </div>
          { loading ? (<div className="flex justify-center items-center mt-[20px]">
            <PacmanLoader
            color="white"
            loading={loading}
            size={15}
            aria-label="Loading Spinner"
            data-testid="loader"
          />
          </div>) : 
          (
            <Post 
            id={tweet?.tweet[0]?.tweet_id} 
            text={tweet?.tweet[0]?.text} 
            media={tweet?.tweet[0]?.media}
            createdAt = {tweet?.tweet[0]?.created_at} 
            username = {router.query['user']}
            />
          )}
         {replies?.replies?.length > 0 && (
            <div className="pb-72">
              {replies?.replies?.map((reply) => (
                <Reply
                  key={reply.tweet_id}
                  tweetId={reply.tweet_id}
                  text= {reply.text}
                  media = {reply.media}
                  username= {reply.user_id.username}
                  createdAt = {reply.created_at}
                  
                />
              ))}
            </div>
          )}
          
      
        <LowerNav toggleSearchSlide={toggleSearchSlide} setToggleSearchSlide={setToggleSearchSlide}/>
        </div>
        {/* Widgets */}
        <RightSidebar/>
        {isModal && <Modal pfp={mainProfile?.pfp} username={tweetData.username}/>}
        {/* Modal */}
      </main>
      
    </>
  )
}


// export async function getServerSideProps(context){
    
//     const id = context.id



//     return {
//         props : {
//             id
//         }
//     }
// }