# Generated by Django 4.2.1 on 2023-06-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='relations',
            index=models.Index(models.F('follower'), models.F('followee'), name='relation_index'),
        ),
    ]
